//Dimitri Papadedes
//Dec 21th
//pokemon swap Jframe
package pokemongui;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Dimitri Papadedes
 */
public class PokemonBattleSwap extends JFrame
{

    PokemonBattle battle;
    Team team;
    
    //image loaders
    ImageIcon sprite;
    URL url;
    
    /**
     * Creates new form PokemonBattleSwap
     * @param pb
     */
    public PokemonBattleSwap(PokemonBattle pb,Team t)
    {
        initComponents();
        battle = pb;
        
        team = t;
        
        //change the button names
        swapPokemonBTN1.setText(team.getBattling().getName());
        swapPokemonBTN2.setText(team.getPoke(1).getName());
        swapPokemonBTN3.setText(team.getPoke(2).getName());
        swapPokemonBTN4.setText(team.getPoke(3).getName());
        swapPokemonBTN5.setText(team.getPoke(4).getName());
        swapPokemonBTN6.setText(team.getPoke(5).getName());
        
        //set Icons
        //get and display the pokemon
        url = PokemonMenu.class.getResource(team.getBattling().getName() +".png");
        sprite = new ImageIcon(url);
        lblPoke1.setIcon(sprite);
      
        
        //other pokemon
        url = PokemonMenu.class.getResource(team.getPoke(1).getName() +".png");
        sprite = new ImageIcon(url);
        lblPoke2.setIcon(sprite);
        url = PokemonMenu.class.getResource(team.getPoke(2).getName() +".png");
        sprite = new ImageIcon(url);
        lblPoke3.setIcon(sprite);
        url = PokemonMenu.class.getResource(team.getPoke(3).getName() +".png");
        sprite = new ImageIcon(url);
        lblPoke4.setIcon(sprite);
        url = PokemonMenu.class.getResource(team.getPoke(4).getName() +".png");
        sprite = new ImageIcon(url);
        lblPoke5.setIcon(sprite);
        url = PokemonMenu.class.getResource(team.getPoke(5).getName() +".png");
        sprite = new ImageIcon(url);
        lblPoke6.setIcon(sprite);
        
        //cant switch to a pokemon that is already out 
        swapPokemonBTN1.setEnabled(false);
        
        //check if the pokemon is dead ,,, if so disable button ,,, if its not disable back button aswell
        if(team.getBattling().getAlive() == false){
            backBTN.setEnabled(false);
        }
            
        if(team.getPoke(1).getAlive() == false){
            swapPokemonBTN2.setEnabled(false);
        }
        
        if(team.getPoke(2).getAlive() == false){
            swapPokemonBTN3.setEnabled(false);
        }
        
        if(team.getPoke(3).getAlive() == false){
            swapPokemonBTN4.setEnabled(false);
        }
        
        if(team.getPoke(4).getAlive() == false){
            swapPokemonBTN5.setEnabled(false);
        }
        
        if(team.getPoke(5).getAlive() == false){
            swapPokemonBTN6.setEnabled(false);
        }
        
        
        //move to the left a bit
        this.setLocation(-1, 145);
 
        
        //set the icon of the frame
        url = PokemonMenu.class.getResource("pokeball.png");
        sprite = new ImageIcon(url);
        setIconImage(sprite.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        swapPokemonBTN1 = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        swapPokemonBTN2 = new javax.swing.JButton();
        swapPokemonBTN3 = new javax.swing.JButton();
        swapPokemonBTN4 = new javax.swing.JButton();
        swapPokemonBTN5 = new javax.swing.JButton();
        swapPokemonBTN6 = new javax.swing.JButton();
        swapPokemonLBL = new javax.swing.JLabel();
        lblPoke1 = new javax.swing.JLabel();
        lblPoke2 = new javax.swing.JLabel();
        lblPoke3 = new javax.swing.JLabel();
        lblPoke4 = new javax.swing.JLabel();
        lblPoke5 = new javax.swing.JLabel();
        lblPoke6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Battle Simulator");
        setBackground(java.awt.Color.lightGray);

        swapPokemonBTN1.setBackground(new java.awt.Color(204, 204, 204));
        swapPokemonBTN1.setFont(new java.awt.Font("Power Green", 1, 30)); // NOI18N
        swapPokemonBTN1.setText("Pokemon 1");
        swapPokemonBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapPokemonBTN1ActionPerformed(evt);
            }
        });

        backBTN.setBackground(new java.awt.Color(153, 153, 153));
        backBTN.setFont(new java.awt.Font("Power Green", 1, 24)); // NOI18N
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), null));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        swapPokemonBTN2.setBackground(new java.awt.Color(204, 204, 204));
        swapPokemonBTN2.setFont(new java.awt.Font("Power Green", 1, 30)); // NOI18N
        swapPokemonBTN2.setText("Pokemon 2");
        swapPokemonBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapPokemonBTN2ActionPerformed(evt);
            }
        });

        swapPokemonBTN3.setBackground(new java.awt.Color(204, 204, 204));
        swapPokemonBTN3.setFont(new java.awt.Font("Power Green", 1, 30)); // NOI18N
        swapPokemonBTN3.setText("Pokemon 3");
        swapPokemonBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapPokemonBTN3ActionPerformed(evt);
            }
        });

        swapPokemonBTN4.setBackground(new java.awt.Color(204, 204, 204));
        swapPokemonBTN4.setFont(new java.awt.Font("Power Green", 1, 30)); // NOI18N
        swapPokemonBTN4.setText("Pokemon 4");
        swapPokemonBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapPokemonBTN4ActionPerformed(evt);
            }
        });

        swapPokemonBTN5.setBackground(new java.awt.Color(204, 204, 204));
        swapPokemonBTN5.setFont(new java.awt.Font("Power Green", 1, 30)); // NOI18N
        swapPokemonBTN5.setText("Pokemon 5");
        swapPokemonBTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapPokemonBTN5ActionPerformed(evt);
            }
        });

        swapPokemonBTN6.setBackground(new java.awt.Color(204, 204, 204));
        swapPokemonBTN6.setFont(new java.awt.Font("Power Green", 1, 30)); // NOI18N
        swapPokemonBTN6.setText("Pokemon 6");
        swapPokemonBTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapPokemonBTN6ActionPerformed(evt);
            }
        });

        swapPokemonLBL.setBackground(java.awt.Color.lightGray);
        swapPokemonLBL.setFont(new java.awt.Font("Power Green", 1, 24)); // NOI18N
        swapPokemonLBL.setText("Swap Pokemon");

        lblPoke1.setMaximumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(swapPokemonLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPoke2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(lblPoke3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoke1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoke4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoke5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoke6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(swapPokemonBTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swapPokemonBTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swapPokemonBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swapPokemonBTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swapPokemonBTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swapPokemonBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(swapPokemonLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(swapPokemonBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(lblPoke1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPoke2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swapPokemonBTN2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPoke3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swapPokemonBTN3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPoke4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swapPokemonBTN4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPoke5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swapPokemonBTN5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(swapPokemonBTN6, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(lblPoke6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backBTNActionPerformed
    {//GEN-HEADEREND:event_backBTNActionPerformed
        //click sound 
        battle.buttonSound.playMusic("Pressing A Sound.wav");
        battle.buttons();
        battle.setVisible(true);
        battle.swap = false;
        this.setVisible(false);
        
    }//GEN-LAST:event_backBTNActionPerformed

    private void swapPokemonBTN1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_swapPokemonBTN1ActionPerformed
    {//GEN-HEADEREND:event_swapPokemonBTN1ActionPerformed
        swap(0);
    }//GEN-LAST:event_swapPokemonBTN1ActionPerformed

    private void swapPokemonBTN2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_swapPokemonBTN2ActionPerformed
    {//GEN-HEADEREND:event_swapPokemonBTN2ActionPerformed
        swap(1);
    }//GEN-LAST:event_swapPokemonBTN2ActionPerformed

    private void swapPokemonBTN3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_swapPokemonBTN3ActionPerformed
    {//GEN-HEADEREND:event_swapPokemonBTN3ActionPerformed
        swap(2);
    }//GEN-LAST:event_swapPokemonBTN3ActionPerformed

    private void swapPokemonBTN4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_swapPokemonBTN4ActionPerformed
    {//GEN-HEADEREND:event_swapPokemonBTN4ActionPerformed
        swap(3);
    }//GEN-LAST:event_swapPokemonBTN4ActionPerformed

    private void swapPokemonBTN5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_swapPokemonBTN5ActionPerformed
    {//GEN-HEADEREND:event_swapPokemonBTN5ActionPerformed
        swap(4);
    }//GEN-LAST:event_swapPokemonBTN5ActionPerformed

    private void swapPokemonBTN6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_swapPokemonBTN6ActionPerformed
    {//GEN-HEADEREND:event_swapPokemonBTN6ActionPerformed
        swap(5);
    }//GEN-LAST:event_swapPokemonBTN6ActionPerformed

    
    
    //swap method
    public void swap(int poke){
        //click sound 
        battle.buttonSound.playMusic("Pressing A Sound.wav");
        battle.type("You switched "  + team.Switch(poke));
        battle.health = team.getBattling().getHp();
        battle.swap = false;
        //close window
        this.setVisible(false);
        //reset 
        battle.reset(team);
        
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel lblPoke1;
    private javax.swing.JLabel lblPoke2;
    private javax.swing.JLabel lblPoke3;
    private javax.swing.JLabel lblPoke4;
    private javax.swing.JLabel lblPoke5;
    private javax.swing.JLabel lblPoke6;
    private javax.swing.JButton swapPokemonBTN1;
    private javax.swing.JButton swapPokemonBTN2;
    private javax.swing.JButton swapPokemonBTN3;
    private javax.swing.JButton swapPokemonBTN4;
    private javax.swing.JButton swapPokemonBTN5;
    private javax.swing.JButton swapPokemonBTN6;
    private javax.swing.JLabel swapPokemonLBL;
    // End of variables declaration//GEN-END:variables
}
