/*
 * Sebastian Latka
 * January 16th, 2020
 * teamBuilder menu
 */
package pokemongui;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.net.URL;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author sebastianlatka
 */
public class PokemonTeamBuilder extends JFrame {

    //makes variables for the forms
    PokemonMenu mainMenu;
    PokemonTeamBuilder teamBuilder;
    PokemonTeamBuilderPokemon teamBuilderPokemon;
    PokemonTeamBuilderMoves teamBuilderMoves;

    //make variables
    private String teamName = "Team 1";
    private int clickIndex;
    static int i = 0, tbPokemonIndex = 0;
    static int[] pokemonIndex = new int[6];
    static String[] holderMoves = new String[6];
    String[] pMove = new String[4], pName, check = new String[6], pokemonString = new String[6];
    Scanner s1;

    PrintWriter out = PokemonMenu.out;

    //create pokemon
    Pokemon[] pokemon;
    //create move
    Move[] move;

    //set fonts
    Font font = new Font("Euphemia UCAS", Font.BOLD, 24);
    Font font2 = new Font("Euphemia UCAS", Font.BOLD, 18);
    //set colours
    Color c = new Color(153, 153, 153);
    //set gridlayout
    GridLayout buttonGrid = new GridLayout(1, 1, 10, 12);

    //create array lists
    ArrayList<JPanel> pnlList = new ArrayList();
    ArrayList<JButton> btnAddList = new ArrayList();
    ArrayList<JButton> btnEditList = new ArrayList();
    ArrayList<JButton> btnDeleteList = new ArrayList();
    static ArrayList<JLabel> lblPokemonNameList = new ArrayList();
    static ArrayList<JLabel> lblSpriteList = new ArrayList();

    //make a team
    Team team;

    //moves for team
    Move[] tMoves = new Move[4];
    static Move mFake = new Move(" ", 0, 0, 0, " ", " ");

    //pokemon for the team
    static Pokemon[] pTeam = new Pokemon[6];
    Pokemon pFake = new Pokemon(" ", 0, 0, 0, 0, 0, 0, mFake, mFake, mFake, mFake, " ", " ");

    static InputStream team1 = null;
    File team1File;

    //sound 
    musicStuff buttonSound = new musicStuff();
    URL url;
    ImageIcon sprite;

    /**
     * Creates new form PokemonTeamBuilder
     *
     */
    public PokemonTeamBuilder(PokemonMenu m, Pokemon pokemon[], Move move[]) {
        initComponents();
        //center
        setLocationRelativeTo(null);
        //set this forms variables equal to the last
        mainMenu = m;
        this.pokemon = pokemon;
        this.move = move;
        team1File = PokemonMenu.team1;
        this.pokemonString = PokemonMenu.pokemonString;

        //set the icon of the frame
        url = PokemonMenu.class.getResource("pokeball.png");
        sprite = new ImageIcon(url);
        setIconImage(sprite.getImage());

        //for loop that gives all possible pokemon a fake move as their moves
        for (int j = 0; j < pokemon.length; j++) {
            for (int k = 1; k < 5; k++) {
                pokemon[j].setMove(mFake, k);
            }
        }

        //for loop that sets the pokemon at pTeam to a fake pokemon
        for (int j = 0; j < pTeam.length; j++) {
            pTeam[j] = pFake;
        }

        //for loop that sets default values to strings and moves so no NullPointerExceptions are thrown
        for (int j = 0; j < tMoves.length; j++) {
            pMove[j] = " ";
            tMoves[j] = mFake;
            holderMoves[j] = " ";
        }

        //checks a boolean that is true if the data file has information inside of it
        if (PokemonMenu.hasSave == true) {
            btnSaveTeam.setText("EditPoke");
            btnDeleteTeam.setEnabled(false);
        } else {
            btnSaveTeam.setText("SaveTeam");
        }

        //calls the createPanelBtns method
        createPanelBtns();
        //disable the edit and delete buttons
        for (int j = 0; j < btnEditList.size(); j++) {
            btnEditList.get(j).setEnabled(false);
            btnDeleteList.get(j).setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTeamBuilder = new javax.swing.JLabel();
        btnDisplay = new javax.swing.JButton();
        pnlPokemon1 = new javax.swing.JPanel();
        pnlPokemonSprite1 = new javax.swing.JPanel();
        lblPokemonSprite1 = new javax.swing.JLabel();
        lblPokemonName1 = new javax.swing.JLabel();
        pnlPokemonBtns1 = new javax.swing.JPanel();
        pnlPokemon2 = new javax.swing.JPanel();
        pnlPokemonSprite2 = new javax.swing.JPanel();
        lblPokemonSprite2 = new javax.swing.JLabel();
        lblPokemonName2 = new javax.swing.JLabel();
        pnlPokemonBtns2 = new javax.swing.JPanel();
        pnlPokemon3 = new javax.swing.JPanel();
        pnlPokemonSprite3 = new javax.swing.JPanel();
        lblPokemonSprite3 = new javax.swing.JLabel();
        lblPokemonName3 = new javax.swing.JLabel();
        pnlPokemonBtns4 = new javax.swing.JPanel();
        pnlPokemon4 = new javax.swing.JPanel();
        pnlPokemonSprite4 = new javax.swing.JPanel();
        lblPokemonSprite4 = new javax.swing.JLabel();
        lblPokemonName4 = new javax.swing.JLabel();
        pnlPokemonBtns11 = new javax.swing.JPanel();
        pnlPokemon5 = new javax.swing.JPanel();
        pnlPokemonSprite5 = new javax.swing.JPanel();
        lblPokemonSprite5 = new javax.swing.JLabel();
        lblPokemonName5 = new javax.swing.JLabel();
        pnlPokemonBtns5 = new javax.swing.JPanel();
        pnlPokemon6 = new javax.swing.JPanel();
        pnlPokemonSprite6 = new javax.swing.JPanel();
        lblPokemonSprite6 = new javax.swing.JLabel();
        lblPokemonName6 = new javax.swing.JLabel();
        pnlPokemonBtns6 = new javax.swing.JPanel();
        cbTeamChooser = new javax.swing.JComboBox<>();
        btnDeleteTeam = new javax.swing.JButton();
        btnSaveTeam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Battle Simulator");
        setBackground(java.awt.Color.lightGray);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Euphemia UCAS", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTeamBuilder.setBackground(java.awt.Color.lightGray);
        lblTeamBuilder.setFont(new java.awt.Font("Euphemia UCAS", 0, 24)); // NOI18N
        lblTeamBuilder.setText(" TeamBuilder");
        lblTeamBuilder.setOpaque(true);

        btnDisplay.setBackground(new java.awt.Color(153, 153, 153));
        btnDisplay.setFont(new java.awt.Font("Euphemia UCAS", 1, 24)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        pnlPokemon1.setBackground(java.awt.Color.lightGray);
        pnlPokemon1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlPokemon1.setMaximumSize(new java.awt.Dimension(765, 68));
        pnlPokemon1.setPreferredSize(new java.awt.Dimension(765, 68));

        pnlPokemonSprite1.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonSprite1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        pnlPokemonSprite1.setMaximumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite1.setMinimumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite1.setPreferredSize(new java.awt.Dimension(68, 68));

        lblPokemonSprite1.setMaximumSize(new java.awt.Dimension(68, 68));
        lblPokemonSprite1.setMinimumSize(new java.awt.Dimension(68, 68));
        lblPokemonSprite1.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlPokemonSprite1Layout = new javax.swing.GroupLayout(pnlPokemonSprite1);
        pnlPokemonSprite1.setLayout(pnlPokemonSprite1Layout);
        pnlPokemonSprite1Layout.setHorizontalGroup(
            pnlPokemonSprite1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPokemonSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPokemonSprite1Layout.setVerticalGroup(
            pnlPokemonSprite1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite1Layout.createSequentialGroup()
                .addComponent(lblPokemonSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblPokemonName1.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblPokemonName1.setMaximumSize(new java.awt.Dimension(132, 68));
        lblPokemonName1.setMinimumSize(new java.awt.Dimension(132, 68));
        lblPokemonName1.setPreferredSize(new java.awt.Dimension(132, 68));

        pnlPokemonBtns1.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonBtns1.setMaximumSize(new java.awt.Dimension(525, 68));
        pnlPokemonBtns1.setMinimumSize(new java.awt.Dimension(525, 68));
        pnlPokemonBtns1.setPreferredSize(new java.awt.Dimension(525, 0));

        javax.swing.GroupLayout pnlPokemonBtns1Layout = new javax.swing.GroupLayout(pnlPokemonBtns1);
        pnlPokemonBtns1.setLayout(pnlPokemonBtns1Layout);
        pnlPokemonBtns1Layout.setHorizontalGroup(
            pnlPokemonBtns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPokemonBtns1Layout.setVerticalGroup(
            pnlPokemonBtns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPokemon1Layout = new javax.swing.GroupLayout(pnlPokemon1);
        pnlPokemon1.setLayout(pnlPokemon1Layout);
        pnlPokemon1Layout.setHorizontalGroup(
            pnlPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon1Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPokemonName1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemonBtns1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPokemon1Layout.setVerticalGroup(
            pnlPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPokemonBtns1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(pnlPokemonSprite1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPokemonName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPokemon2.setBackground(java.awt.Color.lightGray);
        pnlPokemon2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlPokemon2.setMaximumSize(new java.awt.Dimension(765, 68));
        pnlPokemon2.setPreferredSize(new java.awt.Dimension(765, 68));

        pnlPokemonSprite2.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonSprite2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        pnlPokemonSprite2.setMaximumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite2.setMinimumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite2.setPreferredSize(new java.awt.Dimension(68, 68));

        lblPokemonSprite2.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlPokemonSprite2Layout = new javax.swing.GroupLayout(pnlPokemonSprite2);
        pnlPokemonSprite2.setLayout(pnlPokemonSprite2Layout);
        pnlPokemonSprite2Layout.setHorizontalGroup(
            pnlPokemonSprite2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPokemonSprite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPokemonSprite2Layout.setVerticalGroup(
            pnlPokemonSprite2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite2Layout.createSequentialGroup()
                .addComponent(lblPokemonSprite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblPokemonName2.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblPokemonName2.setMaximumSize(new java.awt.Dimension(132, 68));
        lblPokemonName2.setMinimumSize(new java.awt.Dimension(132, 68));
        lblPokemonName2.setPreferredSize(new java.awt.Dimension(132, 68));

        pnlPokemonBtns2.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonBtns2.setMaximumSize(new java.awt.Dimension(525, 68));

        javax.swing.GroupLayout pnlPokemonBtns2Layout = new javax.swing.GroupLayout(pnlPokemonBtns2);
        pnlPokemonBtns2.setLayout(pnlPokemonBtns2Layout);
        pnlPokemonBtns2Layout.setHorizontalGroup(
            pnlPokemonBtns2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPokemonBtns2Layout.setVerticalGroup(
            pnlPokemonBtns2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPokemon2Layout = new javax.swing.GroupLayout(pnlPokemon2);
        pnlPokemon2.setLayout(pnlPokemon2Layout);
        pnlPokemon2Layout.setHorizontalGroup(
            pnlPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon2Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPokemonName2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemonBtns2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPokemon2Layout.setVerticalGroup(
            pnlPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon2Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblPokemonName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPokemonBtns2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPokemon3.setBackground(java.awt.Color.lightGray);
        pnlPokemon3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlPokemon3.setMaximumSize(new java.awt.Dimension(765, 68));

        pnlPokemonSprite3.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonSprite3.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        pnlPokemonSprite3.setMaximumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite3.setMinimumSize(new java.awt.Dimension(68, 68));

        lblPokemonSprite3.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlPokemonSprite3Layout = new javax.swing.GroupLayout(pnlPokemonSprite3);
        pnlPokemonSprite3.setLayout(pnlPokemonSprite3Layout);
        pnlPokemonSprite3Layout.setHorizontalGroup(
            pnlPokemonSprite3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPokemonSprite3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlPokemonSprite3Layout.setVerticalGroup(
            pnlPokemonSprite3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite3Layout.createSequentialGroup()
                .addComponent(lblPokemonSprite3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblPokemonName3.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblPokemonName3.setMaximumSize(new java.awt.Dimension(132, 68));
        lblPokemonName3.setMinimumSize(new java.awt.Dimension(132, 68));
        lblPokemonName3.setPreferredSize(new java.awt.Dimension(132, 68));

        pnlPokemonBtns4.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonBtns4.setMaximumSize(new java.awt.Dimension(525, 68));

        javax.swing.GroupLayout pnlPokemonBtns4Layout = new javax.swing.GroupLayout(pnlPokemonBtns4);
        pnlPokemonBtns4.setLayout(pnlPokemonBtns4Layout);
        pnlPokemonBtns4Layout.setHorizontalGroup(
            pnlPokemonBtns4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPokemonBtns4Layout.setVerticalGroup(
            pnlPokemonBtns4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPokemon3Layout = new javax.swing.GroupLayout(pnlPokemon3);
        pnlPokemon3.setLayout(pnlPokemon3Layout);
        pnlPokemon3Layout.setHorizontalGroup(
            pnlPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon3Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPokemonName3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemonBtns4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPokemon3Layout.setVerticalGroup(
            pnlPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPokemonSprite3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblPokemonName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPokemonBtns4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPokemon4.setBackground(java.awt.Color.lightGray);
        pnlPokemon4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlPokemon4.setMaximumSize(new java.awt.Dimension(765, 68));
        pnlPokemon4.setMinimumSize(new java.awt.Dimension(765, 68));

        pnlPokemonSprite4.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonSprite4.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        pnlPokemonSprite4.setMaximumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite4.setMinimumSize(new java.awt.Dimension(68, 68));

        lblPokemonSprite4.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlPokemonSprite4Layout = new javax.swing.GroupLayout(pnlPokemonSprite4);
        pnlPokemonSprite4.setLayout(pnlPokemonSprite4Layout);
        pnlPokemonSprite4Layout.setHorizontalGroup(
            pnlPokemonSprite4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPokemonSprite4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlPokemonSprite4Layout.setVerticalGroup(
            pnlPokemonSprite4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite4Layout.createSequentialGroup()
                .addComponent(lblPokemonSprite4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblPokemonName4.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblPokemonName4.setMaximumSize(new java.awt.Dimension(132, 68));
        lblPokemonName4.setMinimumSize(new java.awt.Dimension(132, 68));
        lblPokemonName4.setPreferredSize(new java.awt.Dimension(132, 68));

        pnlPokemonBtns11.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonBtns11.setMaximumSize(new java.awt.Dimension(525, 68));

        javax.swing.GroupLayout pnlPokemonBtns11Layout = new javax.swing.GroupLayout(pnlPokemonBtns11);
        pnlPokemonBtns11.setLayout(pnlPokemonBtns11Layout);
        pnlPokemonBtns11Layout.setHorizontalGroup(
            pnlPokemonBtns11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPokemonBtns11Layout.setVerticalGroup(
            pnlPokemonBtns11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPokemon4Layout = new javax.swing.GroupLayout(pnlPokemon4);
        pnlPokemon4.setLayout(pnlPokemon4Layout);
        pnlPokemon4Layout.setHorizontalGroup(
            pnlPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon4Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPokemonName4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemonBtns11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlPokemon4Layout.setVerticalGroup(
            pnlPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon4Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblPokemonName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPokemonBtns11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPokemon5.setBackground(java.awt.Color.lightGray);
        pnlPokemon5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlPokemon5.setMaximumSize(new java.awt.Dimension(765, 68));

        pnlPokemonSprite5.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonSprite5.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        pnlPokemonSprite5.setMaximumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite5.setMinimumSize(new java.awt.Dimension(68, 68));

        lblPokemonSprite5.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlPokemonSprite5Layout = new javax.swing.GroupLayout(pnlPokemonSprite5);
        pnlPokemonSprite5.setLayout(pnlPokemonSprite5Layout);
        pnlPokemonSprite5Layout.setHorizontalGroup(
            pnlPokemonSprite5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPokemonSprite5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlPokemonSprite5Layout.setVerticalGroup(
            pnlPokemonSprite5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite5Layout.createSequentialGroup()
                .addComponent(lblPokemonSprite5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblPokemonName5.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblPokemonName5.setMaximumSize(new java.awt.Dimension(132, 68));
        lblPokemonName5.setMinimumSize(new java.awt.Dimension(132, 68));
        lblPokemonName5.setPreferredSize(new java.awt.Dimension(132, 68));

        pnlPokemonBtns5.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonBtns5.setMaximumSize(new java.awt.Dimension(525, 68));

        javax.swing.GroupLayout pnlPokemonBtns5Layout = new javax.swing.GroupLayout(pnlPokemonBtns5);
        pnlPokemonBtns5.setLayout(pnlPokemonBtns5Layout);
        pnlPokemonBtns5Layout.setHorizontalGroup(
            pnlPokemonBtns5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPokemonBtns5Layout.setVerticalGroup(
            pnlPokemonBtns5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPokemon5Layout = new javax.swing.GroupLayout(pnlPokemon5);
        pnlPokemon5.setLayout(pnlPokemon5Layout);
        pnlPokemon5Layout.setHorizontalGroup(
            pnlPokemon5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon5Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPokemonName5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemonBtns5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPokemon5Layout.setVerticalGroup(
            pnlPokemon5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon5Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblPokemonName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPokemonBtns5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPokemon6.setBackground(java.awt.Color.lightGray);
        pnlPokemon6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlPokemon6.setMaximumSize(new java.awt.Dimension(765, 68));

        pnlPokemonSprite6.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonSprite6.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        pnlPokemonSprite6.setMaximumSize(new java.awt.Dimension(68, 68));
        pnlPokemonSprite6.setMinimumSize(new java.awt.Dimension(68, 68));

        lblPokemonSprite6.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlPokemonSprite6Layout = new javax.swing.GroupLayout(pnlPokemonSprite6);
        pnlPokemonSprite6.setLayout(pnlPokemonSprite6Layout);
        pnlPokemonSprite6Layout.setHorizontalGroup(
            pnlPokemonSprite6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPokemonSprite6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlPokemonSprite6Layout.setVerticalGroup(
            pnlPokemonSprite6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPokemonSprite6Layout.createSequentialGroup()
                .addComponent(lblPokemonSprite6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblPokemonName6.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblPokemonName6.setMaximumSize(new java.awt.Dimension(132, 68));
        lblPokemonName6.setMinimumSize(new java.awt.Dimension(132, 68));
        lblPokemonName6.setPreferredSize(new java.awt.Dimension(132, 68));

        pnlPokemonBtns6.setBackground(new java.awt.Color(204, 204, 204));
        pnlPokemonBtns6.setMaximumSize(new java.awt.Dimension(525, 68));

        javax.swing.GroupLayout pnlPokemonBtns6Layout = new javax.swing.GroupLayout(pnlPokemonBtns6);
        pnlPokemonBtns6.setLayout(pnlPokemonBtns6Layout);
        pnlPokemonBtns6Layout.setHorizontalGroup(
            pnlPokemonBtns6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPokemonBtns6Layout.setVerticalGroup(
            pnlPokemonBtns6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPokemon6Layout = new javax.swing.GroupLayout(pnlPokemon6);
        pnlPokemon6.setLayout(pnlPokemon6Layout);
        pnlPokemon6Layout.setHorizontalGroup(
            pnlPokemon6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPokemon6Layout.createSequentialGroup()
                .addComponent(pnlPokemonSprite6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPokemonName6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemonBtns6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlPokemon6Layout.setVerticalGroup(
            pnlPokemon6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPokemonSprite6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblPokemonName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPokemonBtns6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cbTeamChooser.setBackground(java.awt.Color.lightGray);
        cbTeamChooser.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        cbTeamChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose An Option", "Add Team +" }));
        cbTeamChooser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDeleteTeam.setBackground(new java.awt.Color(153, 153, 153));
        btnDeleteTeam.setFont(new java.awt.Font("Euphemia UCAS", 1, 24)); // NOI18N
        btnDeleteTeam.setText("DeleteTeam");
        btnDeleteTeam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), null));
        btnDeleteTeam.setEnabled(false);
        btnDeleteTeam.setMaximumSize(new java.awt.Dimension(147, 47));
        btnDeleteTeam.setMinimumSize(new java.awt.Dimension(147, 47));
        btnDeleteTeam.setPreferredSize(new java.awt.Dimension(147, 47));
        btnDeleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeamActionPerformed(evt);
            }
        });

        btnSaveTeam.setBackground(new java.awt.Color(153, 153, 153));
        btnSaveTeam.setFont(new java.awt.Font("Euphemia UCAS", 1, 24)); // NOI18N
        btnSaveTeam.setText("SaveTeam");
        btnSaveTeam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), null));
        btnSaveTeam.setEnabled(false);
        btnSaveTeam.setMaximumSize(new java.awt.Dimension(147, 47));
        btnSaveTeam.setMinimumSize(new java.awt.Dimension(147, 47));
        btnSaveTeam.setPreferredSize(new java.awt.Dimension(147, 47));
        btnSaveTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTeamBuilder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 252, Short.MAX_VALUE)
                .addComponent(cbTeamChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplay)
                .addGap(236, 236, 236))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlPokemon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPokemon6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPokemon1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                            .addComponent(pnlPokemon2, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                            .addComponent(pnlPokemon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 763, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTeamBuilder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTeamChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPokemon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeleteTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSaveTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        //play sound
        buttonSound.playMusic("Pressing A Sound.wav");

        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDisplayActionPerformed
    {//GEN-HEADEREND:event_btnDisplayActionPerformed
        //play sound
        buttonSound.playMusic("Pressing A Sound.wav");

        //checks what the item is in the combo box
        if (cbTeamChooser.getSelectedItem() == "Add Team +") {
            if (teamName.equals("Team 1")) {
                cbTeamChooser.insertItemAt(teamName, i + 1);
                i++;
                cbTeamChooser.setSelectedItem(teamName);
                cbTeamChooser.removeItemAt(2);
            }
        }
        //if the selected item is "Team 1"
        if (cbTeamChooser.getSelectedItem() == "Team 1") {
            if (PokemonMenu.hasSave == true) {
                //scan team
                scanTeam();
            }
            //update the gui
            updateGui(0);
            //checks if the add pokemon buttons at index 0 is visible
            if (!btnEditList.get(0).isVisible()) {
                btnAddList.get(0).setVisible(true);
            }
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnDeleteTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteTeamActionPerformed
    {//GEN-HEADEREND:event_btnDeleteTeamActionPerformed
        //play sound
        buttonSound.playMusic("Pressing A Sound.wav");
        //reset the data file
        mainMenu.resetDataFile();
        //scan the team
        scanTeam();;
        //update the gui
        updateGui(0);
        //loop the delete clicks for all the pokemon
        for (int j = 0; j < btnDeleteList.size(); j++) {
            btnDeleteList.get(j).doClick();
            btnAddList.get(j).setVisible(false);
        }
        //disable the button
        btnDeleteTeam.setEnabled(false);
        btnSaveTeam.setEnabled(false);
        btnAddList.get(0).setVisible(true);
    }//GEN-LAST:event_btnDeleteTeamActionPerformed

    private void btnSaveTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveTeamActionPerformed
    {//GEN-HEADEREND:event_btnSaveTeamActionPerformed
        //play sound
        buttonSound.playMusic("Pressing A Sound.wav");
        //changes the text of the button
        if (btnSaveTeam.getText().equals("EditPoke")) {
            btnSaveTeam.setText("SaveTeam");
            btnDeleteTeam.setEnabled(true);
        }

        if (PokemonMenu.hasSave == true) {
            //scan team
            scanTeam();
        }
        //save the team
        saveTeam();
        //write to the data file
        writeFile();
        //make a team
        makeTeam();
        //enable the delete team button
        btnDeleteTeam.setEnabled(true);
        //enable the edit buttons
        for (int j = 0; j < btnEditList.size(); j++) {
            btnEditList.get(j).setEnabled(true);
            btnDeleteList.get(j).setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveTeamActionPerformed

    //method to scan the team1 file
    public void scanTeam() {
        //gets the data file
        team1 = PokemonTeamBuilder.class.getResourceAsStream("team1.txt");

        try {
            //creates a scanner
            s1 = new Scanner(team1);

            //sets the values of pName 
            pName = new String[6];

            //loops the amount of pokemon in a data file
            for (int j = 0; j < pName.length; j++) {
                pName[j] = s1.nextLine();

                url = PokemonMenu.class.getResource(pName[j] + ".png");
                if (url != null) {
                    //if the url is valid then set the items in the form to the correct things depending on the pokemon
                    sprite = new ImageIcon((new ImageIcon(url).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT)));
                    lblSpriteList.get(j).setIcon(sprite);
                    btnAddList.get(j).setVisible(false);
                    btnEditList.get(j).setVisible(true);
                    btnDeleteList.get(j).setVisible(true);
                } else {
                    //if the url isnt a valid png then turn everything off
                    lblSpriteList.get(j).setIcon(null);
                    btnAddList.get(j).setVisible(false);
                    btnEditList.get(j).setVisible(false);
                    btnDeleteList.get(j).setVisible(false);
                }

                //checks if there is a valid pokemon in the data file
                if (!pName[j].equals(" ")) {
                    //if so then set the name of the label to the name of the pokemon from the data file                  
                    lblPokemonNameList.get(j).setText(pName[j]);
                    //sets the moves 
                    for (int k = 0; k < pMove.length; k++) {
                        pMove[k] = s1.nextLine();
                    }
                    holderMoves[j] = pMove[0] + "." + pMove[1] + "." + pMove[2] + "." + pMove[3];
                } else {
                    //sets the pokemon name to nothing of there is no pokemon in the data file
                    lblPokemonNameList.get(j).setText(" ");
                }
            }

        } catch (Exception e) {
            System.out.println("here  " + e);
        }
    }

    //method to save the team to for data file
    public void saveTeam() {

        for (int j = 0; j < pName.length; j++) {
            //make a pokemon based on the name 
            for (int k = 0; k < pokemon.length; k++) {
                //check if the names are equal
                if (pName[j].equals(pokemon[k].getName()) || lblPokemonNameList.get(j).getText().equals(pokemon[k].getName())) {
                    pTeam[j] = pokemon[k];
                    //make the moves
                    for (int l = 0; l < move.length; l++) {
                        if (PokemonMenu.hasSave == true) {
                            //create substrings of the pokemon moves from the data file
                            int startSub = holderMoves[j].indexOf(".");
                            int midSub = holderMoves[j].indexOf(".", startSub + 1);
                            int endSub = holderMoves[j].indexOf(".", midSub + 1);
                            String moveSubString1 = holderMoves[j].substring(0, startSub);
                            startSub++;
                            String moveSubString2 = holderMoves[j].substring(startSub, midSub);
                            midSub++;
                            String moveSubString3 = holderMoves[j].substring(midSub, endSub);
                            endSub++;
                            String moveSubString4 = holderMoves[j].substring(endSub, holderMoves[j].length());

                            //checks if the names of the substrings are equal to any pokemon move and then set it
                            if (moveSubString1.equals(move[l].getName())) {
                                tMoves[0] = move[l];
                            }
                            if (moveSubString2.equals(move[l].getName())) {
                                tMoves[1] = move[l];
                            }
                            if (moveSubString3.equals(move[l].getName())) {
                                tMoves[2] = move[l];
                            }
                            if (moveSubString4.equals(move[l].getName())) {
                                tMoves[3] = move[l];
                            }
                        }
                    }
                }

            }
            if (PokemonMenu.hasSave == true){
            //add the moves to the pokemon
            for (int l = 1; l < 5; l++) {
                pTeam[j].setMove(tMoves[l - 1], l);
            }
            }
        }
    }

    //method to make a team
    public void makeTeam() {
        //make a team
        team = new Player_Team(pTeam[0], pTeam[1], pTeam[2], pTeam[3], pTeam[4], pTeam[5]);
    }

    //methos to swap the screens
    public void swapScreen(int swapIndex) {
        if (swapIndex == 0) {
            teamBuilderPokemon = new PokemonTeamBuilderPokemon(this, pokemon, move);
            teamBuilderPokemon.setVisible(true);
            this.setVisible(false);
        }
        if (swapIndex == 1) {
            teamBuilderPokemon = new PokemonTeamBuilderPokemon(this, pokemon, move);
            this.setVisible(false);
        }
    }

    //method to update the gui buttons
    public void updateGui(int i) {
        if (i == 0) {
            //sets the string check to all the names of the pokemon name labels
            for (int j = 0; j < check.length; j++) {
                check[j] = lblPokemonNameList.get(j).getText();
            }
            //checks if any of the check string are equal to " ", if none are then enable the save team button
            if (!check[0].equals(" ") && !check[1].equals(" ") && !check[2].equals(" ") && !check[3].equals(" ") && !check[4].equals(" ") && !check[5].equals(" ")) {
                btnSaveTeam.setEnabled(true);
            } else {
                btnSaveTeam.setEnabled(false);
            }
            //checks if any of the check string are equal to " " and if the save team button is enebaled
            if (btnSaveTeam.isVisible() && btnSaveTeam.getText().equals("SaveTeam") && !check[0].equals(" ") && !check[1].equals(" ") && !check[2].equals(" ") && !check[3].equals(" ") && !check[4].equals(" ") && !check[5].equals(" ")) {
                btnDeleteTeam.setEnabled(true);
            } else {
                btnDeleteTeam.setEnabled(false);
            }
        } else {
            btnEditList.get(tbPokemonIndex).setEnabled(true);
            btnDeleteList.get(tbPokemonIndex).setEnabled(true);
        }
    }

    //method to create the panels buttons with actionlisteners
    public void createPanelBtns() {
        //add the swing controls to the array lists
        lblSpriteList.add(lblPokemonSprite1);
        lblSpriteList.add(lblPokemonSprite2);
        lblSpriteList.add(lblPokemonSprite3);
        lblSpriteList.add(lblPokemonSprite4);
        lblSpriteList.add(lblPokemonSprite5);
        lblSpriteList.add(lblPokemonSprite6);
        lblPokemonNameList.add(lblPokemonName1);
        lblPokemonNameList.add(lblPokemonName2);
        lblPokemonNameList.add(lblPokemonName3);
        lblPokemonNameList.add(lblPokemonName4);
        lblPokemonNameList.add(lblPokemonName5);
        lblPokemonNameList.add(lblPokemonName6);
        pnlList.add(pnlPokemonBtns1);
        pnlList.add(pnlPokemonBtns2);
        pnlList.add(pnlPokemonBtns4);
        pnlList.add(pnlPokemonBtns11);
        pnlList.add(pnlPokemonBtns5);
        pnlList.add(pnlPokemonBtns6);
        //for loop that runs the amount of pokemon than can be displayed
        for (int i = 0; i < 6; i++) {
            pnlList.get(i).setLayout(buttonGrid);

            //creates a button names Edit
            JButton btnEdit = new JButton("Edit");
            //add the button to the array list
            btnEditList.add(btnEdit);
            //set the properties of the button
            pnlList.get(i).add(btnEdit).setLocation(190, 12);
            pnlList.get(i).add(btnEdit).setSize(120, 48);
            pnlList.get(i).add(btnEdit).setFont(font);
            pnlList.get(i).add(btnEdit).setBackground(c);
            pnlList.get(i).add(btnEdit).setVisible(false);
            //add an action listener so that the button clicks can be registered
            btnEdit.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    //play sound
                    buttonSound.playMusic("Pressing A Sound.wav");

                    clickIndex = btnEditList.indexOf(btnEdit);
                    tbPokemonIndex = clickIndex;
                    //swap screen 1
                    swapScreen(1);
                }
            });

            //creates a button named Delete
            JButton btnDelete = new JButton("Delete");
            //add the button to the array list
            btnDeleteList.add(btnDelete);
            //set the properties of the button
            pnlList.get(i).add(btnDelete).setLocation(345, 12);
            pnlList.get(i).add(btnDelete).setSize(120, 48);
            pnlList.get(i).add(btnDelete).setFont(font);
            pnlList.get(i).add(btnDelete).setBackground(c);
            pnlList.get(i).add(btnDelete).setVisible(false);

            //creates a button name Add Pokemon
            JButton btnAdd = new JButton("Add Pokemon");
            //add the button to the array list
            btnAddList.add(btnAdd);
            //set the properties of the button
            pnlList.get(i).add(btnAdd).setLocation(35, 12);
            pnlList.get(i).add(btnAdd).setSize(120, 12);
            pnlList.get(i).add(btnAdd).setFont(font2);
            pnlList.get(i).add(btnAdd).setBackground(c);
            pnlList.get(i).add(btnAdd).setVisible(false);
            //add an action listener so that the button clicks can be registered
            btnAdd.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    //play sound
                    buttonSound.playMusic("Pressing A Sound.wav");

                    PokemonMenu.hasSave = false;
                    btnSaveTeam.setText("SaveTeam");

                    clickIndex = btnAddList.indexOf(btnAdd);
                    tbPokemonIndex = clickIndex;
                    pokemonIndex[tbPokemonIndex] = clickIndex;
                    //swap screen 0
                    swapScreen(0);
                    //set the buttons in the panel to the correct states
                    btnAddList.get(clickIndex).setVisible(false);
                    btnEditList.get(clickIndex).setVisible(true);
                    btnDeleteList.get(clickIndex).setVisible(true);
                    //sets the add pokemon button at the next index to be visible
                    if (clickIndex < 5) {
                        if (!btnEditList.get(clickIndex + 1).isVisible()) {
                            btnAddList.get(clickIndex + 1).setVisible(true);
                        }
                    }

                }
            });

            //add an action listener so that the button clicks can be registered
            btnDelete.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    //play sound
                    buttonSound.playMusic("Pressing A Sound.wav");

                    clickIndex = btnDeleteList.indexOf(btnDelete);
                    tbPokemonIndex = clickIndex;
                    //set the pokemon label to nothing
                    lblPokemonNameList.get(clickIndex).setText(" ");
                    //updates the gui
                    updateGui(0);
                    //reset the button visiblities
                    btnAddList.get(clickIndex).setVisible(true);
                    btnEditList.get(clickIndex).setVisible(false);
                    btnDeleteList.get(clickIndex).setVisible(false);
                    //set the sprite to nothing
                    lblSpriteList.get(clickIndex).setIcon(null);

                    //reset the pokemon moves
                    try {
                        teamBuilderPokemon.resetMoves();
                    } catch (Exception e) {
                    }
                }
            });
        }
    }

    //start up method to write to the data file
    public void writeFile() {
        try {
            out = new PrintWriter(new FileWriter(team1File));
            writeText();
        } catch (IndexOutOfBoundsException e) {
            System.err.println("Caught IndexOutOfBoundsException: "
                    + e.getMessage());

        } catch (IOException e) {
            System.err.println("Caught IOException: " + e.getMessage());

        } finally {
            if (out != null) {
                out.close();
            } else {
                System.out.println("PrintWriter not open");
            }
        }
    }

    //creates the strings of the pokemon and their moves
    private void setWriteDataFileText(int numOfPokemon) {
        //sets a temporary string to the name of the pokemon and their 4 moves
        String temp = pTeam[numOfPokemon].getName() + "\n" + pTeam[numOfPokemon].getMove(1).getName() + "\n" + pTeam[numOfPokemon].getMove(2).getName() + "\n" + pTeam[numOfPokemon].getMove(3).getName() + "\n" + pTeam[numOfPokemon].getMove(4).getName();
        System.out.println(temp);
        pokemonString[numOfPokemon] = temp;
    }

    //method to set the data file to the correct strings
    private void writeText() {
        setWriteDataFileText(0);
        setWriteDataFileText(1);
        setWriteDataFileText(2);
        setWriteDataFileText(3);
        setWriteDataFileText(4);
        setWriteDataFileText(5);

        //for loop that writes the temporary strings created to the data file
        for (int j = 0; j < pokemonString.length; j++) {
            out.println(pokemonString[j]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteTeam;
    public static javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSaveTeam;
    public static javax.swing.JComboBox<String> cbTeamChooser;
    public static javax.swing.JLabel lblPokemonName1;
    public static javax.swing.JLabel lblPokemonName2;
    public static javax.swing.JLabel lblPokemonName3;
    public static javax.swing.JLabel lblPokemonName4;
    public static javax.swing.JLabel lblPokemonName5;
    public static javax.swing.JLabel lblPokemonName6;
    public static javax.swing.JLabel lblPokemonSprite1;
    public static javax.swing.JLabel lblPokemonSprite2;
    public static javax.swing.JLabel lblPokemonSprite3;
    public static javax.swing.JLabel lblPokemonSprite4;
    public static javax.swing.JLabel lblPokemonSprite5;
    public static javax.swing.JLabel lblPokemonSprite6;
    private javax.swing.JLabel lblTeamBuilder;
    private javax.swing.JPanel pnlPokemon1;
    private javax.swing.JPanel pnlPokemon2;
    private javax.swing.JPanel pnlPokemon3;
    private javax.swing.JPanel pnlPokemon4;
    private javax.swing.JPanel pnlPokemon5;
    private javax.swing.JPanel pnlPokemon6;
    private javax.swing.JPanel pnlPokemonBtns1;
    private javax.swing.JPanel pnlPokemonBtns11;
    private javax.swing.JPanel pnlPokemonBtns2;
    private javax.swing.JPanel pnlPokemonBtns4;
    private javax.swing.JPanel pnlPokemonBtns5;
    private javax.swing.JPanel pnlPokemonBtns6;
    private javax.swing.JPanel pnlPokemonSprite1;
    private javax.swing.JPanel pnlPokemonSprite2;
    private javax.swing.JPanel pnlPokemonSprite3;
    private javax.swing.JPanel pnlPokemonSprite4;
    private javax.swing.JPanel pnlPokemonSprite5;
    private javax.swing.JPanel pnlPokemonSprite6;
    // End of variables declaration//GEN-END:variables
}
